"""initial schema

Revision ID: 3aa967e8489e
Revises: 
Create Date: 2026-04-12 12:48:30.947848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3aa967e8489e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('consultation_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('oss_key', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_segments_consultation_id'), 'audio_segments', ['consultation_id'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('patient_identifier', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_user_id'), 'consultations', ['user_id'], unique=False)
    op.create_table('soap_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('consultation_id', sa.Uuid(), nullable=False),
    sa.Column('subjective', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('assessment', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('medical_entities', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soap_notes_consultation_id'), 'soap_notes', ['consultation_id'], unique=True)
    op.create_table('transcripts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('consultation_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_medically_relevant', sa.Boolean(), nullable=False),
    sa.Column('speaker_label', sa.String(length=20), nullable=True),
    sa.Column('timestamp_start_ms', sa.Integer(), nullable=False),
    sa.Column('timestamp_end_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcripts_consultation_id'), 'transcripts', ['consultation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcripts_consultation_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_soap_notes_consultation_id'), table_name='soap_notes')
    op.drop_table('soap_notes')
    op.drop_index(op.f('ix_consultations_user_id'), table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_audio_segments_consultation_id'), table_name='audio_segments')
    op.drop_table('audio_segments')
    # ### end Alembic commands ###
