"""add soap_note_versions table and patient_identifier index

Revision ID: 4e5c14c20541
Revises: f7d9e2a1b3c5
Create Date: 2026-04-15 09:58:54.679548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e5c14c20541'
down_revision: Union[str, Sequence[str], None] = 'f7d9e2a1b3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soap_note_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('soap_note_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('subjective', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('assessment', sa.Text(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('medical_entities', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('icd10_codes', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('review_flags', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('edited_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('soap_note_id', 'version', name='uq_soap_version')
    )
    op.create_index(op.f('ix_soap_note_versions_soap_note_id'), 'soap_note_versions', ['soap_note_id'], unique=False)
    # Partial index on patient_identifier for patient history queries
    op.execute(
        "CREATE INDEX ix_consultations_patient_identifier "
        "ON consultations(patient_identifier) "
        "WHERE patient_identifier IS NOT NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_consultations_patient_identifier")
    op.drop_index(op.f('ix_soap_note_versions_soap_note_id'), table_name='soap_note_versions')
    op.drop_table('soap_note_versions')
    # ### end Alembic commands ###
