"""add upload mode and processing fields

Revision ID: dd92cc0bf77a
Revises: e68c28e51b31
Create Date: 2026-04-12 22:53:10.372782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd92cc0bf77a'
down_revision: Union[str, Sequence[str], None] = 'e68c28e51b31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('mode', sa.String(length=20), nullable=False))
    op.add_column('consultations', sa.Column('processing_step', sa.String(length=50), nullable=True))
    op.add_column('consultations', sa.Column('processing_progress', sa.Integer(), nullable=False))
    op.add_column('consultations', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('consultations', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultations', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('consultations', 'error_message')
    op.drop_column('consultations', 'processing_progress')
    op.drop_column('consultations', 'processing_step')
    op.drop_column('consultations', 'mode')
    # ### end Alembic commands ###
