"""add transcript status and error_message

Revision ID: eeb4a147c706
Revises: 2e1ad0cc1690
Create Date: 2026-04-13 09:32:15.012313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eeb4a147c706'
down_revision: Union[str, Sequence[str], None] = '2e1ad0cc1690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add with server_default so existing rows get 'classified' (already fully processed).
    op.add_column(
        'transcripts',
        sa.Column('status', sa.String(length=30), nullable=False, server_default='classified'),
    )
    op.add_column('transcripts', sa.Column('error_message', sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'error_message')
    op.drop_column('transcripts', 'status')
    # ### end Alembic commands ###
