"""add emotion column to transcripts

Revision ID: eff2ea357dce
Revises: c3f8a71d5b42
Create Date: 2026-04-13 15:20:06.335153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eff2ea357dce'
down_revision: Union[str, Sequence[str], None] = 'c3f8a71d5b42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcripts', sa.Column('emotion', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcripts', 'emotion')
    # ### end Alembic commands ###
